### ISSUE TITLE
Can't load SimpleOpenNI library (SimpleOpenNI32) : java.lang.UnsatisfiedLinkError:

### ISSUE THREAD

**Issue by GoogleCodeExporter** [wexstorm/simple-openni#58]
```
What steps will reproduce the problem?

1. installation of OpenNI-Windows-x86-2.0.0.32.msi
2. installation of SensorKinect093-Bin-Win32-v5.1.2.1.msi
3. installation of NiTE-Windows-x64-2.0.0(1).msi

4. installation of processing-1.5.1-windows
5. installation of SimpleOpenNI-0.27.zip

What is the expected output? What do you see instead?

I tried to run a SimpleOpenNI exemple. I get this error instead :

Display 0 does not exist, using the default display instead.
Can't load SimpleOpenNI library (SimpleOpenNI32) : 
java.lang.UnsatisfiedLinkError: 
C:\Users\fdiba\Documents\Processing\libraries\SimpleOpenNI\library\SimpleOpenNI3
2.dll: Can't find dependent libraries
Verify if you installed SimpleOpenNI correctly.
http://code.google.com/p/simple-openni/wiki/Installation
Exception in thread "Animation Thread" java.lang.UnsatisfiedLinkError: 
SimpleOpenNI.SimpleOpenNIJNI.swig_module_init()V
    at SimpleOpenNI.SimpleOpenNIJNI.swig_module_init(Native Method)
    at SimpleOpenNI.SimpleOpenNIJNI.<clinit>(SimpleOpenNIJNI.java:1575)
    at SimpleOpenNI.ContextWrapper.<init>(ContextWrapper.java:54)
    at SimpleOpenNI.SimpleOpenNI.<init>(SimpleOpenNI.java:212)
    at RecorderPlay.setup(RecorderPlay.java:46)
    at processing.core.PApplet.handleDraw(Unknown Source)
    at processing.core.PApplet.run(Unknown Source)
    at java.lang.Thread.run(Thread.java:662)

What version of the product are you using?

- OpenNI-Windows-x86-2.0.0.32.msi
- SensorKinect093-Bin-Win32-v5.1.2.1.msi
- NiTE-Windows-x64-2.0.0(1).msi
- processing-1.5.1-windows
- SimpleOpenNI-0.27.zip

On what operating system?

Windows 7 64

Please provide any additional information below.

Can you help me to make it work ? Or give me an other way to use processing and 
kinect ?


```

Original issue reported on code.google.com by `florent....@gmail.com` on 11 Jan 2013 at 8:44

**Comment by wonkyhonky** [comment]
Hi, I _think_ I have a similar problem to this. Have been trying to download and install simpleopenni and nite, to work with processing 3.3.5, on my ubuntu-gnome 17.04. I've got them both to show up in the processing library, but during the install from here: https://code.google.com/archive/p/simple-openni/wikis/Installation.wiki the last instruction for installing the rules came up with  a lot of 404 errors. I'm guessing this is why nothing works when I try to run any of the exapmles through processing. Any thoughts. I'm SO out of my depth here :) :

 wget https://simple-openni.googlecode.com/svn/trunk/SimpleOpenNI-2.0/platform/linux/installLinuxRules.sh wget https://simple-openni.googlecode.com/svn/trunk/SimpleOpenNI-2.0/platform/linux/primesense-usb.rules sudo ./installLinuxRules.sh
--2017-09-02 14:02:59--  https://simple-openni.googlecode.com/svn/trunk/SimpleOpenNI-2.0/platform/linux/installLinuxRules.sh
Resolving simple-openni.googlecode.com (simple-openni.googlecode.com)... 108.177.119.82
Connecting to simple-openni.googlecode.com (simple-openni.googlecode.com)|108.177.119.82|:443... connected.
HTTP request sent, awaiting response... 404 Not Found
2017-09-02 14:02:59 ERROR 404: Not Found.

--2017-09-02 14:02:59--  http://wget/
Resolving wget (wget)... failed: Name or service not known.
wget: unable to resolve host address ‘wget’
--2017-09-02 14:03:00--  https://simple-openni.googlecode.com/svn/trunk/SimpleOpenNI-2.0/platform/linux/primesense-usb.rules
Reusing existing connection to simple-openni.googlecode.com:443.
HTTP request sent, awaiting response... 404 Not Found
2017-09-02 14:03:00 ERROR 404: Not Found.

--2017-09-02 14:03:00--  http://sudo/
Resolving sudo (sudo)... failed: Name or service not known.
wget: unable to resolve host address ‘sudo’
--2017-09-02 14:03:01--  http://./installLinuxRules.sh
Resolving . (.)... failed: Name or service not known.
wget: unable to resolve host address ‘.’
